before_install:
  - sudo add-apt-repository ppa:directhex/monoxide -y
  - sudo apt-get update -qq -y
  - sudo apt-get install mono-devel -qq -y

before_script:
  ./build /p:Configuration=Release /p:Framework=$Framework "/t:DumpSettings;CleanAll"

script: 
  ./build /p:Configuration=Release /p:Framework=$Framework "/t:Build;Test"
  
env:
  matrix:
    - Framework="net-2.0"
    - Framework="net-3.5"
    - Framework="net-4.0"
    - Framework="net-4.5"
    
